#pragma once

#include <windows.h>

///   THIS WAS GENERATED BY COPILOT, MAY BE INACCURATE!!!!!!!!   ///
/// RF Image Information structure containing metadata for strain analysis
typedef struct _RFIMAGEINFO
{
    int nLineNum;               ///< Number of RF lines (height)
    int nBlockNum;              ///< Number of blocks per line (width)
    int nBlockLength;           ///< Samples per block
    int nLineLength;            ///< Total samples per line
    int nBlockSpacing;          ///< Distance between block centers
    int nStartLine;             ///< ROI start line
    int nEndLine;               ///< ROI end line
    int nStartBlock;            ///< ROI start block
    int nEndBlock;              ///< ROI end block
    float fAmplify;             ///< Amplification factor
    unsigned int uStrainLSE;    ///< Strain estimation flag (1=enable)
    BOOL bMedian;               ///< Enable median filtering
    BOOL bLateral;              ///< Enable lateral motion tracking
    BOOL bExtSearch;            ///< Enable extended search
    int nKernelSize;            ///< Median filter kernel size

} RFIMAGEINFO, *LPRFIMAGEINFO;

